context:
  version: 6.3.16

package:
  name: fantomas
  version: ${{ version }}

source:
  url: https://github.com/fsprojects/fantomas/archive/v${{ version }}.tar.gz
  sha256: a825f4135ec8b68f3b6df3106bead149cd8f1ce9ce5e1f509b7deb64941cc1c7

build:
  number: 1
  noarch: generic

requirements:
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - fantomas --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE.md
    - license-files/
  summary: FSharp source code formatter
  homepage: https://fsprojects.github.io/fantomas
  repository: https://github.com/fsprojects/fantomas

extra:
  recipe-maintainers:
    - danielnachun
